############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""      # don't use a slash for home url
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Solutions"
url = "solutions/"
weight = 3

[[main]]
name = "Services"
url = "services/"
weight = 4

[[main]]
name = "More"
hasChildren = true
weight = 5

[[main]]
parent = "More"
name = "Contact"
url = "contact/"
weight = 6

[[main]]
parent = "More"
name = "Pricing"
url = "pricing"
weight = 7

[[main]]
parent = "More"
name = "Blog"
url = "blog/"
weight = 8

#[[footer]]
#name = "About"
#url = "about/"
#weight = 1
#
#[[footer]]
#name = "Pricing"
#url = "pricing/"
#weight = 10
#
[[footer]]
name = "Blog"
url = "blog/"
weight = 20
#
#[[footer]]
#name = "Career"
#url = "career/"
#weight = 30
#
[[footer]]
name = "Contact"
url = "contact/"
weight = 40

[[footer_bottom]]
name = "Privacy Policy"
url = "#"
weight = 1

[[footer_bottom]]
name = "Terms of Use"
url = "#"
weight = 10

[[footer_bottom]]
name = "Legal"
url = "#"
weight = 30

[[footer_bottom]]
name = "Site Map"
url = "#"
weight = 40